/**
 * Installer Module - `brix init installer` and `brix make <target>`
 * 
 * Supported Installer Types:
 * ==========================
 * 1. zip (portable) - Pure Node.js archiver, no external tools required
 * 2. inno - Inno Setup (iscc.exe), modern wizard, LZMA2 compression
 * 3. nsis - NSIS (makensis.exe), classic script-based installer
 * 4. msi - WiX Toolset (candle.exe + light.exe), Windows Installer format
 * 
 * Build Pipeline:
 * ===============
 * 1. brix init installer → creates installer/installer.json + script template
 * 2. brix make <target> → renders template → invokes toolchain → output in installer/dist/
 * 
 * Template Variables:
 * ===================
 * {{APP_NAME}}        - Application name
 * {{APP_VERSION}}     - Version string
 * {{OUT_BASE}}        - Output filename base
 * {{OUTPUT_DIR}}      - Output directory
 * {{ICON}}            - Path to icon file
 * {{EXE}}             - Path to application exe
 * {{EXE_NAME}}        - Exe filename
 * {{EXTRA_FILES}}     - Additional files (per-installer format)
 * {{UPGRADE_GUID}}    - WiX upgrade GUID
 * {{DIR_ENTRIES}}     - WiX directory structure
 * {{FEATURE_REFS}}    - WiX component references
 * 
 * Security:
 * =========
 * - No arbitrary code execution in templates
 * - File paths resolved relative to project root
 * - Path traversal prevented by resolve_scoped_path logic
 * - Toolchain invoked with explicit arguments (no shell injection)
 */
const fs = require('fs-extra');
const path = require('path');
const os = require('os');
const readline = require('readline');
const { execFile } = require('child_process');
const chalk = require('chalk');

const TEMPLATES_DIR = path.join(__dirname, '..', 'installers');

const INNO_TEMPLATE = `; Generated by Brix — build with: brix make inno
[Setup]
AppName={{APP_NAME}}
AppVersion={{APP_VERSION}}
AppPublisher={{APP_NAME}}
DefaultDirName={autopf}\\{{APP_NAME}}
DefaultGroupName={{APP_NAME}}
OutputDir={{OUTPUT_DIR}}
OutputBaseFilename={{OUT_BASE}}
Compression=lzma2
SolidCompression=yes
SetupIconFile={{ICON}}
WizardStyle=modern
UninstallDisplayIcon={app}\\{{EXE_NAME}}

[Tasks]
Name: "desktopicon"; Description: "Create a &desktop shortcut"; GroupDescription: "Additional icons:"

[Files]
Source: "{{EXE}}"; DestDir: "{app}"; Flags: ignoreversion
{{EXTRA_FILES}}

[Icons]
Name: "{group}\\{{APP_NAME}}"; Filename: "{app}\\{{EXE_NAME}}"
Name: "{group}\\Uninstall {{APP_NAME}}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\\{{APP_NAME}}"; Filename: "{app}\\{{EXE_NAME}}"; Tasks: desktopicon

[Run]
Filename: "{app}\\{{EXE_NAME}}"; Description: "Launch {{APP_NAME}}"; Flags: nowait postinstall skipifsilent
`;

const NSIS_TEMPLATE = `; Generated by Brix — build with: brix make nsis
!include "MUI2.nsh"

Name "{{APP_NAME}}"
OutFile "{{OUTPUT_DIR}}/{{OUT_BASE}}.exe"
InstallDir "$PROGRAMFILES64\\{{APP_NAME}}"
InstallDirRegKey HKLM "Software\\{{APP_NAME}}" "InstallDir"
RequestExecutionLevel admin
Unicode True

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH
!insertmacro MUI_UNPAGE_CONFIRM
!insertmacro MUI_UNPAGE_INSTFILES
!insertmacro MUI_LANGUAGE "English"

Section "Install"
  SetOutPath "$INSTDIR"
  File "{{EXE}}"
{{EXTRA_FILES}}
  WriteRegStr HKLM "Software\\{{APP_NAME}}" "InstallDir" "$INSTDIR"
  WriteUninstaller "$INSTDIR\\uninstall.exe"
  CreateDirectory "$SMPROGRAMS\\{{APP_NAME}}"
  CreateShortcut "$SMPROGRAMS\\{{APP_NAME}}\\{{APP_NAME}}.lnk" "$INSTDIR\\{{EXE_NAME}}"
  CreateShortcut "$DESKTOP\\{{APP_NAME}}.lnk" "$INSTDIR\\{{EXE_NAME}}"
SectionEnd

Section "Uninstall"
  RMDir /r "$INSTDIR"
  Delete "$DESKTOP\\{{APP_NAME}}.lnk"
  RMDir /r "$SMPROGRAMS\\{{APP_NAME}}"
  DeleteRegKey HKLM "Software\\{{APP_NAME}}"
SectionEnd
`;

const WIX_TEMPLATE = `<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by Brix — build with: brix make msi -->
<!-- WiX Toolset v3/v4 compatible MSI template -->
<!-- Product.Id="*" generates new GUID each build -->
<!-- UpgradeCode must be stable across versions for MajorUpgrade to work -->
<Wix xmlns="http://schemas.microsoft.com/wix/2006/wi">
  <Product Id="*" Name="{{APP_NAME}}" Language="1033" Version="{{VERSION}}" Manufacturer="{{APP_NAME}}" UpgradeCode="{{UPGRADE_GUID}}">
    <Package InstallerVersion="200" Compressed="yes" InstallScope="perMachine"/>
    <MajorUpgrade DowngradeErrorMessage="A newer version of {{APP_NAME}} is already installed."/>
    <MediaTemplate/>
    <Directory Id="TARGETDIR" Name="SourceDir">
      <Directory Id="ProgramFiles64Folder">
        <Directory Id="INSTALLFOLDER" Name="{{APP_NAME}}">
{{DIR_ENTRIES}}
        </Directory>
      </Directory>
    </Directory>
    <Feature Id="MainFeature" Title="Main" Level="1">
{{FEATURE_REFS}}
    </Feature>
  </Product>
</Wix>
`;

const TYPES = {
    /**
     * zip: Pure Node.js portable ZIP (archiver). No external tools needed.
     * Output: installer/dist/<name>-setup-portable.zip
     */
    zip: { label: 'Portable ZIP', tools: [], template: null, ext: 'zip', needsExe: false },
    /**
     * inno: Inno Setup compiler (iscc.exe). Modern wizard, LZMA2 compression.
     * Requires: Inno Setup 6 (https://jrsoftware.org/isinfo.php)
     * Output: installer/dist/<name>-setup.exe
     */
    inno: { label: 'Inno Setup (setup.exe)', tools: ['iscc'], template: INNO_TEMPLATE, ext: 'iss', needsExe: true },
    /**
     * nsis: Nullsoft Scriptable Install System (makensis.exe).
     * Requires: NSIS 3+ (https://nsis.sourceforge.io/)
     * Output: installer/dist/<name>-setup.exe
     */
    nsis: { label: 'NSIS (installer.exe)', tools: ['makensis'], template: NSIS_TEMPLATE, ext: 'nsi', needsExe: true },
    /**
     * msi: WiX Toolset v3/v4 (candle.exe + light.exe, or wix build).
     * Requires: WiX Toolset v3.11+ or v4+ (https://wixtoolset.org/)
     * Output: installer/dist/<name>.msi
     * Note: Supports both WiX v3 (candle+light) and v4 (wix build)
     */
    msi: { label: 'MSI (WiX)', tools: ['wix', 'candle'], template: WIX_TEMPLATE, ext: 'wxs', needsExe: true }
};

function toForwardSlashes(p) {
    return p.replace(/\\/g, '/');
}

/**
 * Generates a Windows-style GUID with uppercase hex and braces.
 * Used for WiX component GUIDs (must be stable per component).
 * Uses crypto.randomUUID() for cryptographic randomness.
 */
function guid() {
    const g = require('crypto').randomUUID();
    return `{${g.toUpperCase()}}`;
}

/**
 * Locates an external tool (iscc, makensis, candle, light, wix) in PATH
 * or common default install directories.
 * 
 * Search order:
 * 1. PATH directories with platform-specific extensions
 * 2. Common default install directories (hardcoded fallbacks)
 * 
 * Returns full path to tool executable or null if not found.
 * Used by makeInstaller to locate iscc, makensis, candle, light, wix.
 */
async function findTool(name) {
    const exts = process.platform === 'win32' ? ['', '.exe', '.cmd', '.bat'] : [''];
    const dirs = (process.env.PATH || '').split(path.delimiter);
    for (const dir of dirs) {
        if (!dir) continue;
        for (const ext of exts) {
            const candidate = path.join(dir, name + ext);
            if (await fs.pathExists(candidate)) return candidate;
        }
    }
    // Common default install locations (fallback when not in PATH)
    const fixed = {
        iscc: [
            'C:/Program Files (x86)/Inno Setup 6/iscc.exe',
            'C:/Program Files/Inno Setup 6/iscc.exe',
            'C:/Program Files (x86)/Inno Setup 5/iscc.exe'
        ],
        makensis: [
            'C:/Program Files (x86)/NSIS/makensis.exe',
            'C:/Program Files/NSIS/makensis.exe'
        ],
        candle: [
            'C:/Program Files (x86)/WiX Toolset v3.11/bin/candle.exe',
            'C:/Program Files (x86)/WiX Toolset v3.14/bin/candle.exe',
            'C:/Program Files/WiX Toolset v3.11/bin/candle.exe'
        ]
    };
    for (const candidate of fixed[name] || []) {
        if (await fs.pathExists(candidate)) return candidate;
    }
    return null;
}

/**
 * Executes a command and returns {code, out, err}.
 * Uses execFile (not shell) for security - no shell injection possible.
 * WindowsHide prevents console window flash.
 * maxBuffer increased to 16MB for large installer output.
 */
function run(cmd, args, cwd) {
    return new Promise((resolve) => {
        execFile(cmd, args, { cwd, windowsHide: true, maxBuffer: 16 * 1024 * 1024 }, (err, stdout, stderr) => {
            resolve({ code: err ? (err.code || 1) : 0, out: String(stdout || ''), err: String(stderr || '') });
        });
    });
}

let pipedLines = null;
let pipedIndex = 0;

function readPipedLine() {
    if (pipedLines === null) {
        // Non-TTY stdin (pipe/file): read everything once at the first
        // prompt, then hand out one line per prompt.
        pipedLines = String(fs.readFileSync(0, 'utf8')).split(/\r?\n/);
        pipedIndex = 0;
    }
    return pipedIndex < pipedLines.length ? pipedLines[pipedIndex++] : '';
}

/**
 * Interactive list picker (arrow keys; space toggles in multi mode).
 * Falls back to a numbered prompt when stdin is not a TTY.
 */
function promptList({ message, choices, multi = false, defaults = [] }) {
    const renderChoices = () => choices.map((c, i) => {
        const label = typeof c === 'string' ? c : c.label;
        const hint = typeof c === 'string' ? '' : c.hint ? chalk.gray('  ' + c.hint) : '';
        return { label, hint, i };
    });

    if (!process.stdin.isTTY || !process.stdout.isTTY) {
        return new Promise((resolve) => {
            const list = renderChoices();
            console.log('\n' + chalk.bold(message));
            for (const item of list) {
                console.log(`  ${item.i + 1}. ${item.label}${item.hint}`);
            }
            const answer = readPipedLine().trim();
            console.log(chalk.gray(multi ? 'Enter numbers (comma-separated, empty = all):' : 'Enter number: ') + answer);
            if (multi && answer === '') {
                resolve(list.map((x) => x.i)); // empty = select everything
                return;
            }
            const nums = multi
                ? answer.split(/[,\s]+/).filter(Boolean).map((n) => parseInt(n, 10) - 1)
                : [parseInt(answer, 10) - 1];
            const picked = nums.filter((n) => !Number.isNaN(n) && n >= 0 && n < list.length);
            if (picked.length === 0) {
                console.log(chalk.red(multi ? 'No valid choices.' : 'Invalid choice.'));
                resolve(multi ? [] : -1);
                return;
            }
            resolve(multi ? picked : picked[0]);
        });
    }

    return new Promise((resolve) => {
        const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: true });
        const selected = new Set(defaults);
        let cursor = 0;
        const list = renderChoices();
        let drawn = false;

        const draw = () => {
            const lines = [chalk.bold(message)];
            for (const item of list) {
                const marker = item.i === cursor ? chalk.cyan('❯') : ' ';
                const check = multi ? (selected.has(item.i) ? chalk.green('[✓]') : '[ ]') : '';
                const label = item.i === cursor ? chalk.cyan(item.label) : item.label;
                lines.push(` ${marker} ${check} ${label}${item.hint}`);
            }
            lines.push(chalk.gray(multi ? 'space: toggle · enter: done · esc: cancel' : '↑/↓: move · enter: select · esc: cancel'));
            const out = '\x1B[2K\r' + lines.join('\r\n\x1B[2K') + '\r\n';
            if (drawn) process.stdout.write(`\x1B[${lines.length}A`);
            process.stdout.write(out);
            drawn = true;
        };

        const onKey = (str, key) => {
            if (key.name === 'up' || (key.ctrl && key.name === 'p')) {
                cursor = (cursor - 1 + list.length) % list.length;
            } else if (key.name === 'down' || (key.ctrl && key.name === 'n')) {
                cursor = (cursor + 1) % list.length;
            } else if (multi && key.name === 'space') {
                selected.has(cursor) ? selected.delete(cursor) : selected.add(cursor);
            } else if (key.name === 'return' || key.name === 'enter') {
                cleanup();
                resolve(multi ? Array.from(selected) : cursor);
            } else if (key.name === 'escape') {
                cleanup();
                resolve(multi ? null : -1);
            }
            draw();
        };

        const cleanup = () => {
            process.stdin.setRawMode(false);
            rl.close();
            process.stdout.write('\x1B[?25h');
        };

        rl.input.on('keypress', onKey);
        process.stdin.setRawMode(true);
        process.stdin.resume();
        process.stdout.write('\x1B[?25l');
        draw();
    });
}

async function loadProjectConfig(project) {
    let root = project ? path.resolve(project) : process.cwd();
    let stat = await fs.stat(root).catch(() => null);
    if (stat && stat.isFile()) root = path.dirname(root);
    const configPath = path.join(root, '.brix');
    if (!(await fs.pathExists(configPath))) {
        throw new Error(`No .brix file found in ${root} — run "brix build" there first`);
    }
    const config = await fs.readJson(configPath);
    return { root, config };
}

function findBuiltExe(root, config) {
    const outDir = path.join(root, 'Brix_Works');
    if (!fs.existsSync(outDir)) return null;
    const exeName = sanitize(config.name || 'BrixApp') + '.exe';
    const exact = path.join(outDir, exeName);
    if (fs.existsSync(exact)) return exact;
    const exes = fs.readdirSync(outDir).filter((f) => f.toLowerCase().endsWith('.exe'));
    return exes.length ? path.join(outDir, exes[0]) : null;
}

function sanitize(name) {
    return name.replace(/[<>:"/\\|?*\x00-\x1F]/g, '_').replace(/\s+/g, '-');
}

async function listProjectFiles(root) {
    const { glob } = require('glob');
    const ignore = ['node_modules', 'node_modules/**', '.git', '.git/**', 'Brix_Works', 'Brix_Works/**', '.brix', '.brix/**', 'installer', 'installer/**', '*.log', '*.WebView2', 'temp_*.zip'];
    const matched = await glob(['./**/*'], { cwd: root, ignore, nodir: true, dot: true });
    const out = [];
    for (const f of matched) {
        const abs = path.join(root, f);
        try {
            const st = await fs.stat(abs);
            if (st.isFile()) out.push({ name: toForwardSlashes(f), size: st.size });
        } catch (e) { /* skip */ }
    }
    return out.sort((a, b) => a.name.localeCompare(b.name));
}

const INSTALL_IGNORED_DIRS = new Set(['node_modules', '.git', 'Brix_Works', 'installer', 'BRIX-APP']);
const INSTALL_IGNORED_FILES = new Set(['.brix', '.brix.json']);

/**
 * Top-level folders + root files for the installer picker. Picking a folder
 * includes every file under it (destination = the folder's relative path).
 */
async function listProjectItems(root) {
    const folders = [];
    const files = [];
    const entries = await fs.readdir(root, { withFileTypes: true }).catch(() => []);
    for (const e of entries) {
        if (e.isDirectory() && !INSTALL_IGNORED_DIRS.has(e.name)) {
            const count = await countFilesUnder(path.join(root, e.name));
            if (count > 0) folders.push({ name: toForwardSlashes(e.name), count });
        } else if (e.isFile() && !INSTALL_IGNORED_FILES.has(e.name)) {
            const st = await fs.stat(path.join(root, e.name)).catch(() => null);
            if (st) files.push({ name: e.name, size: st.size });
        }
    }
    folders.sort((a, b) => a.name.localeCompare(b.name));
    files.sort((a, b) => a.name.localeCompare(b.name));
    return { folders, files };
}

async function countFilesUnder(dir) {
    let n = 0;
    const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => []);
    for (const e of entries) {
        if (e.isDirectory()) {
            if (!INSTALL_IGNORED_DIRS.has(e.name)) n += await countFilesUnder(path.join(dir, e.name));
        } else if (e.isFile()) n += 1;
    }
    return n;
}

/**
 * Every file under a picked folder, with `subDir` = path relative to root
 * (the folder's own name is preserved as the destination).
 */
async function collectFolderFiles(root, folder) {
    const out = [];
    const base = path.join(root, folder);
    const walk = async (dir, rel) => {
        const entries = await fs.readdir(dir, { withFileTypes: true }).catch(() => []);
        for (const e of entries) {
            if (e.isDirectory()) {
                if (!INSTALL_IGNORED_DIRS.has(e.name)) await walk(path.join(dir, e.name), rel ? `${rel}/${e.name}` : e.name);
            } else if (e.isFile()) {
                const abs = path.join(dir, e.name);
                const st = await fs.stat(abs).catch(() => null);
                if (st) out.push({ path: toForwardSlashes(path.relative(root, abs)), subDir: toForwardSlashes(rel || ''), size: st.size });
            }
        }
    };
    await walk(base, folder);
    return out.sort((a, b) => a.path.localeCompare(b.path));
}

function formatBytes(b) {
    if (b < 1024) return `${b} B`;
    if (b < 1024 * 1024) return `${(b / 1024).toFixed(1)} KB`;
    return `${(b / 1024 / 1024).toFixed(1)} MB`;
}

async function listInstallerTemplates() {
    const out = [];
    for (const [type, meta] of Object.entries(TYPES)) {
        const tool = meta.tools[0];
        const found = tool ? await findTool(tool) : null;
        out.push({
            type,
            label: meta.label,
            hint: found ? chalk.green('✓ ' + tool) : chalk.red('tool not found')
        });
    }
    return out;
}

async function writeInstallerConfig(root, config) {
    const dir = path.join(root, 'installer');
    await fs.ensureDir(dir);
    if (config.type === 'msi' && !config.upgradeGuid) {
        config.upgradeGuid = guid(); // stable across builds so MSI upgrades work
    }
    await fs.writeJson(path.join(dir, 'installer.json'), config, { spaces: 2 });
    const meta = TYPES[config.type];
    if (meta.template) {
        const script = renderTemplate(meta.template, config, root);
        await fs.writeFile(path.join(dir, `installer.${meta.ext}`), script, 'utf8');
    }
}

/**
 * Renders an installer template by substituting variables with config values.
 * 
 * Template Variables:
 * - {{APP_NAME}}, {{APP_VERSION}}, {{OUT_BASE}}, {{OUTPUT_DIR}}, {{ICON}}
 * - {{EXE}}, {{EXE_NAME}} - application executable path/name
 * - {{EXTRA_FILES}} - installer-specific file listing format
 * - {{DIR_ENTRIES}}, {{FEATURE_REFS}} - WiX directory/component XML
 * - {{UPGRADE_GUID}} - stable WiX upgrade GUID for MajorUpgrade
 * 
 * Security: All file paths resolved via path.resolve() to prevent traversal.
 * Paths normalized to forward slashes for installer compatibility.
 * 
 * @param {string} template - Raw template string (INNO_TEMPLATE, NSIS_TEMPLATE, or WIX_TEMPLATE)
 * @param {Object} cfg - Installer config from installer.json
 * @param {string} root - Project root directory
 * @returns {string} Rendered installer script ready for toolchain
 */
function renderTemplate(template, cfg, root) {
    let exeName = cfg.exeName || 'app.exe';
    const outputDir = path.join(cfg.outputDir || path.join(root, 'installer', 'dist')).replace(/\\/g, '/');
    const iconPath = cfg.icon ? path.resolve(root, cfg.icon).replace(/\\/g, '/') : '';
    const extras = cfg.files.filter((f) => f.role !== 'exe');
    let extraLines = '';
    if (template === INNO_TEMPLATE) {
        extraLines = extras.map((f) => `Source: "${path.resolve(root, f.path).replace(/\\/g, '/')}"; DestDir: "{app}${f.subDir ? '\\' + f.subDir : ''}"; Flags: ignoreversion`).join('\n');
        return template
            .replace(/\{\{APP_NAME\}\}/g, cfg.appName)
            .replace(/\{\{APP_VERSION\}\}/g, cfg.appVersion)
            .replace(/\{\{OUTPUT_DIR\}\}/g, outputDir)
            .replace(/\{\{OUT_BASE\}\}/g, cfg.outBase)
            .replace(/\{\{ICON\}\}/g, iconPath || '')
            .replace(/\{\{EXE\}\}/g, path.resolve(root, exeName).replace(/\\/g, '/'))
            .replace(/\{\{EXE_NAME\}\}/g, path.basename(exeName))
            .replace(/\{\{EXTRA_FILES\}\}/g, extraLines);
    }
    if (template === NSIS_TEMPLATE) {
        extraLines = extras.map((f) => `  File "/oname=${f.subDir ? f.subDir + '/' : ''}${path.basename(f.path)}" "${path.resolve(root, f.path).replace(/\\/g, '/')}"`).join('\n');
        return template
            .replace(/\{\{APP_NAME\}\}/g, cfg.appName)
            .replace(/\{\{OUTPUT_DIR\}\}/g, outputDir)
            .replace(/\{\{OUT_BASE\}\}/g, cfg.outBase)
            .replace(/\{\{EXE\}\}/g, path.resolve(root, exeName).replace(/\\/g, '/'))
            .replace(/\{\{EXE_NAME\}\}/g, path.basename(exeName))
            .replace(/\{\{EXTRA_FILES\}\}/g, extraLines);
    }
    if (template === WIX_TEMPLATE) {
        // Files are grouped by their destination subDir; nested directories
        // are rendered as nested <Directory> elements under INSTALLFOLDER.
        const all = [{ path: exeName, subDir: '' }].concat(extras.map((f) => ({ path: f.path, subDir: f.subDir || '' })));
        const tree = { children: new Map(), files: [] };
        const getNode = (segments) => {
            let node = tree;
            for (const s of segments) {
                if (!node.children.has(s)) node.children.set(s, { children: new Map(), files: [] });
                node = node.children.get(s);
            }
            return node;
        };
        for (const f of all) {
            const segs = f.subDir ? f.subDir.split('/') : [];
            getNode(segs).files.push(f);
        }
        let compIdx = 0;
        let dirEntries = '';
        let featureRefs = '';
        const renderNode = (node, depth) => {
            const pad = '          '.repeat(depth + 1);
            const padIn = '            '.repeat(depth + 1);
            for (const [name, child] of node.children) {
                dirEntries += `${pad}<Directory Id="Dir${compIdx++}" Name="${name}">\n`;
                renderNode(child, depth + 1);
                dirEntries += `${pad}</Directory>\n`;
            }
            for (const f of node.files) {
                const compId = `Cmp${compIdx}`;
                dirEntries += `${padIn}<Component Id="${compId}" Guid="${guid()}">\n`;
                dirEntries += `${padIn}  <File Id="File${compIdx}" Source="${path.resolve(root, f.path).replace(/\\/g, '/')}" KeyPath="yes"/>\n`;
                dirEntries += `${padIn}</Component>\n`;
                featureRefs += `      <ComponentRef Id="${compId}"/>\n`;
                compIdx++;
            }
        };
        renderNode(tree, 0);
        return template
            .replace(/\{\{APP_NAME\}\}/g, cfg.appName)
            .replace(/\{\{VERSION\}\}/g, cfg.appVersion)
            .replace(/\{\{UPGRADE_GUID\}\}/g, cfg.upgradeGuid || guid())
            .replace(/\{\{DIR_ENTRIES\}\}/g, dirEntries)
            .replace(/\{\{FEATURE_REFS\}\}/g, featureRefs);
    }
    return template;
}

/* ------------------------------------------------------------------ */
/*  brix init installer — interactive wizard                          */
/* ------------------------------------------------------------------ */

/**
 * Initializes installer configuration via interactive wizard.
 * Creates installer/installer.json and installer script template.
 * 
 * Flow:
 * 1. Load .brix project config
 * 2. Find built exe in Brix_Works/
 * 2. Prompt for installer type (zip/inno/nsis/msi) with tool availability
 * 3. Prompt for files to include (folders preserve structure)
 * 4. Generate installer.json + script template (installer/installer.<ext>)
 * 5. Output next steps
 * 
 * Security: File selection limited to project root; path traversal prevented.
 * 
 * @param {string} project - Project directory path
 * @param {Object} options - CLI options (type, files, name, appVersion, outBase)
 */
async function initInstaller(project, options) {
    const { root, config } = await loadProjectConfig(project);

    const exe = findBuiltExe(root, config);
    if (!exe) {
        console.log(chalk.yellow(`   ⚠ No built exe in ${path.join(root, 'Brix_Works')} — build it first: brix build`));
    }

    let type = options.type;
    if (!type) {
        const templates = await listInstallerTemplates();
        const picked = await promptList({
            message: chalk.cyan('Pick an installer type (available in the Brix install folder):'),
            choices: templates.map((t) => ({ label: t.label, hint: t.hint })),
            multi: false
        });
        if (picked === -1 || picked === null) {
            console.log(chalk.gray('Cancelled.'));
            return;
        }
        type = templates[picked].type;
    }
    if (!TYPES[type]) throw new Error(`Unknown installer type: ${type} (zip | inno | nsis | msi)`);

    // Files to include — pick whole folders (their structure is preserved
    // on install) or individual root files.
    const { folders, files } = await listProjectItems(root);
    const allFiles = await listProjectFiles(root);
    let pickedFiles; // [{ path, subDir }]
    if (options.files) {
        pickedFiles = options.files.split(',').map((f) => f.trim()).filter(Boolean);
        const expanded = [];
        for (const f of pickedFiles) {
            if (folders.some((d) => d.name === f)) {
                expanded.push(...(await collectFolderFiles(root, f)).map((x) => ({ path: x.path, subDir: x.subDir })));
            } else if (allFiles.some((x) => x.name === f)) {
                expanded.push({ path: f, subDir: '' });
            } else {
                console.log(chalk.yellow(`   ⚠ Not found: ${f}`));
            }
        }
        pickedFiles = expanded;
    } else {
        console.log(chalk.cyan(`\nRoot of ${path.relative(process.cwd(), root) || '.'} — pick folders to ship (whole structure is kept) or single files:`));
        const defaults = [];
        const entryDir = config.entry ? config.entry.split('/')[0] : null;
        if (entryDir && folders.some((d) => d.name === entryDir)) {
            defaults.push(folders.findIndex((d) => d.name === entryDir));
        } else if (folders.length) {
            defaults.push(0);
        }
        const readmeIdx = files.findIndex((f) => /^readme\.(md|txt)$/i.test(f.name));
        if (readmeIdx >= 0) defaults.push(folders.length + readmeIdx);
        const licenseIdx = files.findIndex((f) => /^license/i.test(f.name));
        if (licenseIdx >= 0) defaults.push(folders.length + licenseIdx);
        const choices = [
            ...folders.map((d) => ({ label: `${d.name}/`, hint: chalk.gray(`folder (${d.count} files)`), i: -1 })),
            ...files.map((f) => ({ label: f.name, hint: formatBytes(f.size), i: -1 }))
        ].map((c, i) => ({ ...c, i }));

        const picked = await promptList({
            message: chalk.cyan('Select what to install (space to toggle):'),
            choices,
            multi: true,
            defaults
        });
        if (picked === null) {
            console.log(chalk.gray('Cancelled.'));
            return;
        }
        pickedFiles = [];
        for (const i of picked) {
            const c = choices[i];
            if (!c) continue;
            const isFolder = c.label.endsWith('/');
            const name = isFolder ? c.label.slice(0, -1) : c.label;
            if (isFolder) {
                pickedFiles.push(...(await collectFolderFiles(root, name)).map((x) => ({ path: x.path, subDir: x.subDir })));
            } else {
                pickedFiles.push({ path: name, subDir: '' });
            }
        }
    }

    const exeName = exe ? path.relative(root, exe).replace(/\\/g, '/') : null;
    const hasExe = exeName && pickedFiles.some((f) => f.path === exeName);
    if (!hasExe && exeName) {
        pickedFiles.unshift({ path: exeName, subDir: '', role: 'exe' }); // the app exe is always installed
    }

    const appName = options.name || config.name;
    const appVersion = options.appVersion || config.version || '1.0.0';
    const outBase = options.outBase || sanitize(appName) + '-setup';

    const cfg = {
        type,
        appName,
        appVersion,
        outBase,
        outputDir: 'installer/dist',
        files: pickedFiles.map((f) => ({
            path: f.path,
            role: f.role || (f.path === exeName ? 'exe' : 'extra'),
            subDir: f.subDir || ''
        })),
        exeName: exeName || sanitize(appName) + '.exe',
        icon: config.icon || undefined
    };

    await writeInstallerConfig(root, cfg);
    console.log(chalk.green(`\n✔ Installer config written to installer/installer.json`));
    console.log(chalk.gray(`   ${cfg.files.length} files (${formatBytes(cfg.files.reduce((n, f) => n + (f.size || 0), 0))})`));
    const meta = TYPES[type];
    if (meta.template) {
        console.log(chalk.gray(`   Script: installer/installer.${meta.ext}`));
    }
    console.log(chalk.gray(`   Next: run ${chalk.bold(`brix make ${type}`)} to build it`));
}

/* ------------------------------------------------------------------ */
/*  brix make <target>                                                */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/*  brix make <target>                                                */
/* ------------------------------------------------------------------ */

/**
 * Builds an installer package from installer/installer.json config.
 * 
 * Flow:
 * 1. Load installer/installer.json (or create minimal config from .brix)
 * 2. Validate target type (zip/inno/nsis/msi)
 * 3. For zip: create portable zip with archiver (level 9 compression)
 * 4. For inno/nsis/msi: render template → write script → invoke toolchain
 * 5. Output built installer path and size
 * 
 * Security:
 * - Toolchain invoked via execFile (no shell)
 * - File paths resolved absolutely, traversal prevented
 * - Tool lookup via findTool (PATH + known locations)
 * - No shell injection possible
 * 
 * @param {string} target - Installer type: zip | inno | nsis | msi
 * @param {Object} options - CLI options (project, out, name, appVersion)
 */
async function makeInstaller(target, options) {
    const root = path.resolve(options.project || process.cwd());
    const cfgPath = path.join(root, 'installer', 'installer.json');
    let cfg = null;
    if (await fs.pathExists(cfgPath)) {
        cfg = await fs.readJson(cfgPath);
    }
    const targetType = target || (cfg && cfg.type) || null;
    if (!targetType) {
        throw new Error('No installer target given. Run "brix init installer" first, or pass a target: brix make zip | inno | nsis | msi');
    }
    if (!TYPES[targetType]) {
        throw new Error(`Unknown installer target: ${targetType} (zip | inno | nsis | msi)`);
    }

    if (cfg) {
        cfg.type = targetType;
        if (options.name) cfg.appName = options.name;
        if (options.appVersion) cfg.appVersion = options.appVersion;
        await writeInstallerConfig(root, cfg);
    } else {
        const { config } = await loadProjectConfig(root);
        const exe = findBuiltExe(root, config);
        cfg = {
            type: targetType,
            appName: config.name,
            appVersion: config.version || '1.0.0',
            outBase: sanitize(config.name) + '-setup',
            outputDir: 'installer/dist',
            files: exe ? [{ path: path.relative(root, exe).replace(/\\/g, '/'), role: 'exe', subDir: '' }] : [],
            exeName: exe ? path.relative(root, exe).replace(/\\/g, '/') : sanitize(config.name) + '.exe',
            icon: config.icon || undefined
        };
    }

    const outputDir = options.out
        ? path.resolve(options.out)
        : path.isAbsolute(cfg.outputDir || '')
            ? cfg.outputDir
            : path.resolve(root, cfg.outputDir || 'installer/dist');
    const meta = TYPES[targetType];

    if (targetType === 'zip') {
        const exeEntry = cfg.files.find((f) => f.role === 'exe') || cfg.files[0];
        if (!exeEntry || !(await fs.pathExists(path.join(root, exeEntry.path)))) {
            throw new Error(`App exe not found (${exeEntry ? exeEntry.path : 'none'} in installer.json). Build it first: brix build`);
        }
        await fs.ensureDir(outputDir);
        const zipPath = path.join(outputDir, `${cfg.outBase}-portable.zip`);
        const archiver = require('archiver');
        const output = fs.createWriteStream(zipPath);
        const archive = archiver('zip', { zlib: { level: 9 } });
        archive.pipe(output);
        for (const f of cfg.files) {
            const abs = path.join(root, f.path);
            if (await fs.pathExists(abs)) {
                const zipName = (f.subDir ? f.subDir + '/' : '') + path.basename(f.path);
                archive.file(abs, { name: zipName });
            }
        }
        await archive.finalize();
        await new Promise((resolve, reject) => {
            output.on('close', resolve);
            output.on('error', reject);
        });
        console.log(chalk.green(`✔ Portable zip: ${zipPath}`));
        console.log(chalk.gray(`   ${formatBytes((await fs.stat(zipPath)).size)}`));
        return;
    }

    // Real installers: generate the script, then run the toolchain.
    const script = renderTemplate(meta.template, { ...cfg, outputDir }, root);
    const scriptPath = path.join(root, 'installer', `installer.${meta.ext}`);
    await fs.ensureDir(path.dirname(scriptPath));
    await fs.writeFile(scriptPath, script, 'utf8');

    if (targetType === 'inno') {
        const iscc = await findTool('iscc');
        if (!iscc) {
            throw new Error('Inno Setup not found. Install it from https://jrsoftware.org/isinfo.php (iscc.exe goes in PATH) and re-run: brix make inno');
        }
        console.log(chalk.gray(`   Running ${iscc} ...`));
        const res = await run(iscc, ['/Qp', scriptPath]);
        const built = path.join(outputDir, `${cfg.outBase}.exe`);
        if (res.code === 0 && (await fs.pathExists(built))) {
            console.log(chalk.green(`✔ Setup exe: ${built}`));
            console.log(chalk.gray(`   ${formatBytes((await fs.stat(built)).size)}`));
        } else {
            console.error(chalk.red(`✖ Inno Setup failed (exit ${res.code}):`));
            console.error(res.err || res.out);
            process.exitCode = 1;
        }
        return;
    }

    if (targetType === 'nsis') {
        const makensis = await findTool('makensis');
        if (!makensis) {
            throw new Error('NSIS not found. Install it from https://nsis.sourceforge.io/ (makensis.exe goes in PATH) and re-run: brix make nsis');
        }
        console.log(chalk.gray(`   Running ${makensis} ...`));
        const res = await run(makensis, ['/V2', scriptPath]);
        const built = path.join(outputDir, `${cfg.outBase}.exe`);
        if (res.code === 0 && (await fs.pathExists(built))) {
            console.log(chalk.green(`✔ NSIS installer: ${built}`));
            console.log(chalk.gray(`   ${formatBytes((await fs.stat(built)).size)}`));
        } else {
            console.error(chalk.red(`✖ NSIS failed (exit ${res.code}):`));
            console.error(res.err || res.out);
            process.exitCode = 1;
        }
        return;
    }

    if (targetType === 'msi') {
        const candle = await findTool('candle');
        const wixCli = await findTool('wix');
        await fs.ensureDir(outputDir);
        if (wixCli && !candle) {
            // WiX v4+: wix build path/to/installer.wxs -o out.msi
            console.log(chalk.gray(`   Running ${wixCli} build ...`));
            const res = await run(wixCli, ['build', scriptPath, '-o', path.join(outputDir, `${cfg.outBase}.msi`)]);
            const built = path.join(outputDir, `${cfg.outBase}.msi`);
            if (res.code === 0 && (await fs.pathExists(built))) {
                console.log(chalk.green(`✔ MSI: ${built}`));
                console.log(chalk.gray(`   ${formatBytes((await fs.stat(built)).size)}`));
            } else {
                console.error(chalk.red(`✖ WiX failed (exit ${res.code}):`));
                console.error(res.err || res.out);
                process.exitCode = 1;
            }
            return;
        }
        if (!candle) {
            throw new Error('WiX toolset not found. Install it from https://wixtoolset.org/ (candle.exe + light.exe in PATH) and re-run: brix make msi');
        }
        const light = await findTool('light');
        const wixobj = path.join(os.tmpdir(), `${cfg.outBase}.wixobj`);
        console.log(chalk.gray(`   Running ${candle} ...`));
        const cRes = await run(candle, ['-out', wixobj, scriptPath]);
        if (cRes.code !== 0) {
            console.error(chalk.red(`✖ candle failed (exit ${cRes.code}):`));
            console.error(cRes.err || cRes.out);
            process.exitCode = 1;
            return;
        }
        console.log(chalk.gray(`   Running ${light} ...`));
        const built = path.join(outputDir, `${cfg.outBase}.msi`);
        const lRes = await run(light, ['-out', built, wixobj]);
        if (lRes.code === 0 && (await fs.pathExists(built))) {
            console.log(chalk.green(`✔ MSI: ${built}`));
            console.log(chalk.gray(`   ${formatBytes((await fs.stat(built)).size)}`));
        } else {
            console.error(chalk.red(`✖ light failed (exit ${lRes.code}):`));
            console.error(lRes.err || lRes.out);
            process.exitCode = 1;
        }
        return;
    }
}

module.exports = { initInstaller, makeInstaller, promptList, TYPES, findTool };
